//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predictor.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Predictor.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;WeatherAtTimes&quot;:{&quot;12&quot;:{&quot;lat&quot;:42.5345,&quot;lon&quot;:-83.0856,&quot;timezone&quot;:&quot;America/Detroit&quot;,&quot;timezone_offset&quot;:-14400,&quot;data&quot;:[{&quot;dt&quot;:1715788800,&quot;sunrise&quot;:1715767799,&quot;sunset&quot;:1715820456,&quot;temp&quot;:66.54,&quot;feels_like&quot;:65.86,&quot;pressure&quot;:1010.0,&quot;humidity&quot;:63.0,&quot;dew_point&quot;:53.56,&quot;uvi&quot;:0.0,&quot;clouds&quot;:0.0,&quot;visibility&quot;:10000.0,&quot;wind_speed&quot;:9.22,&quot;wind_gust&quot;:0.0,&quot;wind_deg&quot;:40.0,&quot;weather&quot;:[{&quot;id&quot;:500,&quot;main&quot;:&quot;Rain&quot;,&quot;description&quot;:&quot;light rain&quot;,&quot;icon&quot;:&quot;10d&quot;}]}]},&quot;15&quot;:{&quot;lat&quot;:42.5345,&quot;lon&quot;:-83.0856,&quot;timezone&quot;:&quot;America/Detroit&quot;,&quot;timezone_offset [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeatherData_05152024 {
            get {
                return ResourceManager.GetString("WeatherData_05152024", resourceCulture);
            }
        }
    }
}
