//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Predictor.Testing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Predictor.Testing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:&quot;1&quot;,&quot;table&quot;:&quot;trevor smi&quot;,&quot;guests&quot;:1,&quot;order_type_id&quot;:18,&quot;revenue_center_id&quot;:42,&quot;revenue_center_name&quot;:&quot;Online Ordering&quot;,&quot;owner_id&quot;:30,&quot;owner_name&quot;:&quot;Online O.&quot;,&quot;owner_timecard_id&quot;:&quot;45417.0838412963&quot;,&quot;time_opened&quot;:&quot;2024-05-05T11:04:51.851&quot;,&quot;opener_id&quot;:30,&quot;opener_name&quot;:&quot;Online O.&quot;,&quot;opened_station_id&quot;:1,&quot;time_closed&quot;:&quot;2024-05-05T11:04:52.021&quot;,&quot;closer_id&quot;:30,&quot;closer_name&quot;:&quot;Online O.&quot;,&quot;closer_timecard_id&quot;:&quot;45417.0838412963&quot;,&quot;closed_station_id&quot;:1,&quot;flags&quot;:{&quot;used&quot;:true,&quot;tab_name_entered&quot;:true},&quot;total&quot;:18.71,&quot;ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CheckListModelExample {
            get {
                return ResourceManager.GetString("CheckListModelExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;10:00&quot;,&quot;10:10&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:10&quot;,&quot;10:20&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:20&quot;,&quot;10:30&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:30&quot;,&quot;10:40&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:40&quot;,&quot;10:50&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:50&quot;,&quot;11:00&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;11:00&quot;,&quot;11:10&quot;,&quot;1&quot;,&quot;1&quot;,&quot;6.75&quot;,&quot;6.75&quot;
        ///&quot;11:10&quot;,&quot;11:20&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;6.75&quot;
        ///&quot;11:20&quot;,&quot;11:30&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;6.75&quot;
        ///&quot;11:30&quot;,&quot;11:40&quot;,&quot;2&quot;,&quot;2&quot;,&quot;8.30&quot;,&quot;15.05&quot;
        ///&quot;11:40&quot;,&quot;11:50&....
        /// </summary>
        internal static string EmailOnePm {
            get {
                return ResourceManager.GetString("EmailOnePm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;10:00&quot;,&quot;10:10&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:10&quot;,&quot;10:20&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:20&quot;,&quot;10:30&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:30&quot;,&quot;10:40&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:40&quot;,&quot;10:50&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:50&quot;,&quot;11:00&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;11:00&quot;,&quot;11:10&quot;,&quot;1&quot;,&quot;1&quot;,&quot;6.75&quot;,&quot;6.75&quot;
        ///&quot;11:10&quot;,&quot;11:20&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;6.75&quot;
        ///&quot;11:20&quot;,&quot;11:30&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;6.75&quot;
        ///&quot;11:30&quot;,&quot;11:40&quot;,&quot;2&quot;,&quot;2&quot;,&quot;8.30&quot;,&quot;15.05&quot;
        ///&quot;11:40&quot;,&quot;11:50&....
        /// </summary>
        internal static string EmailThreePm {
            get {
                return ResourceManager.GetString("EmailThreePm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;10:00&quot;,&quot;10:10&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:10&quot;,&quot;10:20&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:20&quot;,&quot;10:30&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:30&quot;,&quot;10:40&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:40&quot;,&quot;10:50&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;10:50&quot;,&quot;11:00&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;0.00&quot;
        ///&quot;11:00&quot;,&quot;11:10&quot;,&quot;1&quot;,&quot;1&quot;,&quot;6.75&quot;,&quot;6.75&quot;
        ///&quot;11:10&quot;,&quot;11:20&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;6.75&quot;
        ///&quot;11:20&quot;,&quot;11:30&quot;,&quot;0&quot;,&quot;0&quot;,&quot;0.00&quot;,&quot;6.75&quot;
        ///&quot;11:30&quot;,&quot;11:40&quot;,&quot;2&quot;,&quot;2&quot;,&quot;8.30&quot;,&quot;15.05&quot;
        ///&quot;11:40&quot;,&quot;11:50&....
        /// </summary>
        internal static string EmailTwoPm {
            get {
                return ResourceManager.GetString("EmailTwoPm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;date&quot;:&quot;2024-01-01&quot;,&quot;localName&quot;:&quot;New Year&apos;s Day&quot;,&quot;name&quot;:&quot;New Year&apos;s Day&quot;,&quot;countryCode&quot;:&quot;US&quot;,&quot;fixed&quot;:false,&quot;global&quot;:true,&quot;counties&quot;:null,&quot;launchYear&quot;:null,&quot;types&quot;:[&quot;Public&quot;]},{&quot;date&quot;:&quot;2024-01-15&quot;,&quot;localName&quot;:&quot;Martin Luther King, Jr. Day&quot;,&quot;name&quot;:&quot;Martin Luther King, Jr. Day&quot;,&quot;countryCode&quot;:&quot;US&quot;,&quot;fixed&quot;:false,&quot;global&quot;:true,&quot;counties&quot;:null,&quot;launchYear&quot;:null,&quot;types&quot;:[&quot;Public&quot;]},{&quot;date&quot;:&quot;2024-02-19&quot;,&quot;localName&quot;:&quot;Washington&apos;s Birthday&quot;,&quot;name&quot;:&quot;Presidents Day&quot;,&quot;countryCode&quot;:&quot;US&quot;,&quot;fixed&quot;:false,&quot;global&quot;:true,&quot;counti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Holidays2024 {
            get {
                return ResourceManager.GetString("Holidays2024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales_Three_Pm,TempNoon,FeelsLikeNoon,PressureNoon,HumidityNoon,DewPointNoon,UviNoon,CloudsNoon,VisibilityNoon,WindSpeedNoon,WindGustNoon,WindDegNoon,TempThree,FeelsLikeThree,PressureThree,HumidityThree,DewPointThree,UviThree,CloudsThree,VisibilityThree,WindSpeedThree,WindGustThree,WindDegThree,TempSix,TempNine,Noon_Raining,Three_Raining,Six_Raining,Nine_Raining,Noon_Snowing,Three_Snowing,Six_Snowing,Nine_Snowing,First_Order_Minutes_In_Day,Last_Order_Minutes_In_Day,WeekDayNumber,DayOfMonth,Month,Year,Julian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PredictorFeatures {
            get {
                return ResourceManager.GetString("PredictorFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;WeatherAtTimes&quot;:{&quot;12&quot;:{&quot;lat&quot;:42.5345,&quot;lon&quot;:-83.0856,&quot;timezone&quot;:&quot;America/Detroit&quot;,&quot;timezone_offset&quot;:-14400,&quot;data&quot;:[{&quot;dt&quot;:1715788800,&quot;sunrise&quot;:1715767799,&quot;sunset&quot;:1715820456,&quot;temp&quot;:66.54,&quot;feels_like&quot;:65.86,&quot;pressure&quot;:1010.0,&quot;humidity&quot;:63.0,&quot;dew_point&quot;:53.56,&quot;uvi&quot;:0.0,&quot;clouds&quot;:0.0,&quot;visibility&quot;:10000.0,&quot;wind_speed&quot;:9.22,&quot;wind_gust&quot;:0.0,&quot;wind_deg&quot;:40.0,&quot;weather&quot;:[{&quot;id&quot;:500,&quot;main&quot;:&quot;Rain&quot;,&quot;description&quot;:&quot;light rain&quot;,&quot;icon&quot;:&quot;10d&quot;}]}]},&quot;15&quot;:{&quot;lat&quot;:42.5345,&quot;lon&quot;:-83.0856,&quot;timezone&quot;:&quot;America/Detroit&quot;,&quot;timezone_offset [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WeatherData_05152024 {
            get {
                return ResourceManager.GetString("WeatherData_05152024", resourceCulture);
            }
        }
    }
}
